#!/usr/bin/env bash
# =====================================================================
# T2S v1.0 — one-command local install (Mac / arm64 Docker).
#
#   ./install.sh                 # zero-arg: does EVERYTHING (2 demo DBs, CPU embeddings)
#   ./install.sh --port 8080     # optional: change the UI/API host port
#   ./install.sh --llm-api-base http://127.0.0.1:1234 --llm-api-key sk-... --llm-model openai/qwen
#   ./install.sh --embedding-api-base http://127.0.0.1:1234 --embedding-model openai/my-embed --embedding-dimension 768
#   ./install.sh --no-tests      # skip bringing up the benchmark test platform
#
# Brings up: Postgres (separate container, pre-seeded with BOTH demo DBs:
#            sports_events_large + cybermarket_pattern_large) +
#            Embeddings (separate container: Qwen3-Embedding-0.6B, auto GPU/CPU) +
#            T2S app (FalkorDB + frontend) +
#            the benchmark test platform (separate containers; not executed).
# Then indexes BOTH Postgres DBs into graphs and loads their knowledge + rules.
#
# Embeddings: ZERO-CONFIG — if you pass no --embedding-* flag, T2S uses the
# bundled CPU embedding container (no external service needed). Pass an endpoint
# to use a faster/hosted OpenAI-compatible embedding instead.
# Only the COMPLETION LLM is always external (defaults to LM Studio on the host).
#
# NOTE: default host port is 5050 — macOS AirPlay Receiver occupies port 5000.
# =====================================================================
set -euo pipefail
cd "$(dirname "$0")"

# ---- defaults (all optional to override) ----
PORT=5050
LLM_BASE="http://host.docker.internal:1234/v1"
LLM_KEY="lm-studio"                 # placeholder; pass --llm-api-key for a real key
LLM_MODEL="openai/gemma-4-12b-it-qat"
EMB_BASE=""                         # empty => bundled CPU embedding container
EMB_KEY=""
EMB_MODEL=""
EMB_DIM=""
WITH_TESTS=true

while [ "$#" -gt 0 ]; do
  case "$1" in
    --port)               PORT="${2:?}"; shift 2 ;;
    --llm-api-base)       LLM_BASE="${2:?}"; shift 2 ;;
    --llm-api-key)        LLM_KEY="${2:?}"; shift 2 ;;
    --llm-model)          LLM_MODEL="${2:?}"; shift 2 ;;
    --embedding-api-base) EMB_BASE="${2:?}"; shift 2 ;;
    --embedding-api-key)  EMB_KEY="${2:?}"; shift 2 ;;
    --embedding-model)    EMB_MODEL="${2:?}"; shift 2 ;;
    --embedding-dimension) EMB_DIM="${2:?}"; shift 2 ;;
    --no-tests)           WITH_TESTS=false; shift ;;
    -h|--help)            sed -n '2,27p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown arg: $1 (see --help)" >&2; exit 1 ;;
  esac
done

# A container can't reach the Mac host via localhost/127.0.0.1; rewrite to
# host.docker.internal so a host service is reachable. Append /v1 if missing.
norm_base() {
  local b="${1//127.0.0.1/host.docker.internal}"; b="${b//localhost/host.docker.internal}"
  case "$b" in */v1|*/v1/) ;; *) b="${b%/}/v1" ;; esac
  printf '%s' "$b"
}
LLM_BASE="$(norm_base "$LLM_BASE")"
[ -n "$EMB_BASE" ] && EMB_BASE="$(norm_base "$EMB_BASE")"

APP="http://localhost:${PORT}"
echo "[t2s] port=$PORT  llm=$LLM_MODEL @ $LLM_BASE"
if [ -n "$EMB_BASE" ]; then
  echo "[t2s] embeddings: $EMB_MODEL @ $EMB_BASE (external)"
else
  echo "[t2s] embeddings: bundled CPU container (Qwen3-Embedding-0.6B) — no setup needed"
fi

# ---- 1. .env (completion/memory LLM + optional embedding override) ----
SECRET="$(openssl rand -hex 32 2>/dev/null || python3 -c 'import secrets;print(secrets.token_hex(32))')"
cat > .env <<EOF
# Generated by install.sh — do not commit.
FASTAPI_SECRET_KEY=$SECRET
AUTH_DISABLED=true
COMPLETION_API_BASE=$LLM_BASE
COMPLETION_API_KEY=$LLM_KEY
COMPLETION_MODEL=$LLM_MODEL
COMPLETION_TEMPERATURE=0.0
COMPLETION_MAX_TOKENS=8000
MEMORY_API_BASE=$LLM_BASE
MEMORY_API_KEY=$LLM_KEY
MEMORY_COMPLETION_MODEL=$LLM_MODEL
MEMORY_MAX_TOKENS=8000
LLM_TIMEOUT_SECONDS=300
EOF
# Embedding override ONLY if requested; otherwise compose defaults to the bundled
# CPU container (see docker-compose.yml EMBEDDING_* substitution).
if [ -n "$EMB_BASE" ]; then
  {
    echo "EMBEDDING_API_BASE=$EMB_BASE"
    [ -n "$EMB_KEY" ]   && echo "EMBEDDING_API_KEY=$EMB_KEY"
    [ -n "$EMB_MODEL" ] && echo "EMBEDDING_MODEL=$EMB_MODEL"
    [ -n "$EMB_DIM" ]   && echo "EMBEDDING_DIMENSION=$EMB_DIM"
  } >> .env
fi

# ---- 2. build + start Postgres (seeds BOTH demo DBs) + embeddings + T2S ----
echo "[t2s] building image + starting stack (first build is large: torch + embed model)..."
APP_PORT="$PORT" docker compose up -d --build postgres embeddings t2s

# ---- 3. wait for the app to become healthy (healthcheck runs INSIDE the
#         container, so it is immune to host-port conflicts like AirPlay :5000) ----
echo "[t2s] waiting for t2s-app to become healthy (embedding model load + warmup)..."
ready=false
for _ in $(seq 1 200); do
  st="$(docker inspect -f '{{.State.Health.Status}}' t2s-app 2>/dev/null || echo starting)"
  [ "$st" = healthy ]   && { ready=true; break; }
  [ "$st" = unhealthy ] && { echo "[t2s] container unhealthy — see: docker compose logs t2s" >&2; break; }
  sleep 3
done
[ "$ready" = true ] || { echo "[t2s] app did not become healthy; check: docker compose logs t2s" >&2; exit 1; }

# ---- 4. index BOTH demo DBs into graphs + load each DB's knowledge + rules ----
index_db() {
  local DBNAME="$1" KB_FILE="$2"
  local URL="postgresql://t2s:t2s@postgres:5432/${DBNAME}"
  # clean slate: drop any existing graph for this DB so a re-run re-indexes cleanly
  for g in $(docker exec t2s-app redis-cli GRAPH.LIST 2>/dev/null | grep -E "(^|_)${DBNAME}\$" || true); do
    docker exec t2s-app redis-cli GRAPH.DELETE "$g" >/dev/null 2>&1 && echo "[t2s] dropped existing graph $g"
  done
  echo "[t2s] indexing $DBNAME (schema graph + embeddings + value/JSON grounding)..."
  docker compose exec -T t2s python - "$URL" <<'PY'
import json, sys, urllib.request
req = urllib.request.Request("http://127.0.0.1:5000/database",
    data=json.dumps({"url": sys.argv[1]}).encode(),
    headers={"Content-Type": "application/json"}, method="POST")
with urllib.request.urlopen(req, timeout=3600) as r:
    out = r.read().decode("utf-8", "replace").replace("|||FALKORDB_MESSAGE_BOUNDARY|||", "\n")
    sys.stdout.write(out[-400:])
PY
  echo
  echo "[t2s] loading knowledge + user-rules for $DBNAME ..."
  docker compose exec -T t2s python - "$DBNAME" "$KB_FILE" <<'PY'
import json, os, sys, urllib.request
graph, kb = sys.argv[1], sys.argv[2]
items = [(f"/app/business-rules/{kb}", "knowledge", "knowledge"),
         ("/app/business-rules/user_rules.md", "user_rules", "user-rules")]
for path, key, ep in items:
    if not os.path.exists(path):
        print("[t2s] skip (missing)", path); continue
    req = urllib.request.Request(f"http://127.0.0.1:5000/graphs/{graph}/{ep}",
        data=json.dumps({key: open(path).read()}).encode(),
        headers={"Content-Type": "application/json"}, method="PUT")
    try:
        urllib.request.urlopen(req, timeout=180); print("[t2s] loaded", os.path.basename(path))
    except Exception as e:
        print("[t2s] skip", path, e)
PY
}

index_db sports_events_large       sports_business_knowledge.md
index_db cybermarket_pattern_large cyber_business_knowledge.md

# ---- 5. benchmark test platform (separate containers, configured for T2S; NOT run) ----
if [ "$WITH_TESTS" = true ] && [ -x test-platform/setup-t2s.sh ]; then
  echo "[t2s] setting up benchmark test platform (configured against T2S; not executed)..."
  test-platform/setup-t2s.sh || echo "[t2s] test platform setup reported issues — see above"
fi

echo
echo "================= T2S READY ================="
echo " UI / API : $APP/"
echo " API docs : $APP/openapi.json"
echo " DBs      : sports_events_large (Formula-1, 61 tables) + cybermarket_pattern_large (marketplace, 56 tables)"
if [ -n "$EMB_BASE" ]; then
  echo " Embedding: $EMB_MODEL @ $EMB_BASE (external)"
else
  echo " Embedding: bundled container t2s-embeddings (Qwen3-Embedding-0.6B, auto GPU/CPU)"
fi
echo " LLM      : $LLM_MODEL @ $LLM_BASE  (external — ensure it is running)"
[ "$WITH_TESTS" = true ] && echo " Tests    : http://localhost:8090/  (benchmark platform, configured; run from its UI)"
echo "============================================="
