"""Merge-style schema refresh: the database is the fact, enrichment survives.

Refreshing a db-backed graph must NOT be drop-and-reload: that loses the
YAML/LLM business descriptions, declared REFERENCES links, rules and
knowledge. This module introspects the executable database and merges:

- NEW tables/columns are added (description from the DB comment when present,
  otherwise generated by the LLM from the table context and user rules);
- data types / nullability are updated from the database (DB is the fact);
- tables/columns that vanished from the database are removed with their edges;
- existing non-empty descriptions and REFERENCES links are preserved;
- compact value previews (sample_values) are collected for filter-like
  columns that don't have them yet.

No domain hardcode: introspection uses the engine's standard catalog,
classification is type/metadata-driven only.
"""

from __future__ import annotations

import json
import logging
from typing import Any, Optional

from api.loaders.yaml_loader import (
    _is_sample_candidate,
    _quote_sql_identifier,
)


def _normalize(value: Any) -> str:
    return str(value or "").strip()


def _introspect_database(loader_class, db_url: str, db_type: str, db_name: str) -> dict:
    """Return {table_name: {columns: {name: {type, nullable, key, comment}}}}.

    Uses the engine catalog through the loader's own execute_sql_query —
    no separate connection stack.
    """
    tables: dict[str, dict] = {}

    if db_type == "impala":
        rows = loader_class.execute_sql_query(f"SHOW TABLES IN {db_name}", db_url)
        names = [list(row.values())[0] for row in rows if row]
        for short_name in names:
            full = f"{db_name}.{short_name}"
            described = loader_class.execute_sql_query(f"DESCRIBE {full}", db_url)
            columns: dict[str, dict] = {}
            for row in described:
                col = _normalize(row.get("name"))
                if not col or col.startswith("#"):
                    continue
                columns[col] = {
                    "type": _normalize(row.get("type")),
                    "nullable": "unknown",
                    "key": "",
                    "comment": _normalize(row.get("comment")),
                }
            if columns:
                tables[full] = {"columns": columns}
        return tables

    if db_type in {"postgresql", "postgres"}:
        sql = """
            SELECT c.table_schema, c.table_name, c.column_name, c.data_type,
                   c.is_nullable,
                   pgd.description AS comment,
                   CASE WHEN kcu.column_name IS NOT NULL THEN 'PRI' ELSE '' END AS key
            FROM information_schema.columns c
            LEFT JOIN pg_catalog.pg_statio_all_tables st
              ON st.schemaname = c.table_schema AND st.relname = c.table_name
            LEFT JOIN pg_catalog.pg_description pgd
              ON pgd.objoid = st.relid AND pgd.objsubid = c.ordinal_position
            LEFT JOIN information_schema.table_constraints tc
              ON tc.table_schema = c.table_schema AND tc.table_name = c.table_name
             AND tc.constraint_type = 'PRIMARY KEY'
            LEFT JOIN information_schema.key_column_usage kcu
              ON kcu.constraint_name = tc.constraint_name
             AND kcu.table_schema = c.table_schema
             AND kcu.table_name = c.table_name
             AND kcu.column_name = c.column_name
            WHERE c.table_schema NOT IN ('pg_catalog', 'information_schema')
            ORDER BY c.table_schema, c.table_name, c.ordinal_position
        """
        for row in loader_class.execute_sql_query(sql, db_url):
            full = f"{_normalize(row.get('table_schema'))}.{_normalize(row.get('table_name'))}"
            col = _normalize(row.get("column_name"))
            if not col:
                continue
            tables.setdefault(full, {"columns": {}})["columns"][col] = {
                "type": _normalize(row.get("data_type")),
                "nullable": _normalize(row.get("is_nullable")) or "unknown",
                "key": _normalize(row.get("key")),
                "comment": _normalize(row.get("comment")),
            }
        return tables

    if db_type == "mysql":
        sql = """
            SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_TYPE,
                   IS_NULLABLE, COLUMN_KEY, COLUMN_COMMENT
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA NOT IN
                ('mysql', 'information_schema', 'performance_schema', 'sys')
            ORDER BY TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION
        """
        for row in loader_class.execute_sql_query(sql, db_url):
            full = f"{_normalize(row.get('TABLE_SCHEMA'))}.{_normalize(row.get('TABLE_NAME'))}"
            col = _normalize(row.get("COLUMN_NAME"))
            if not col:
                continue
            tables.setdefault(full, {"columns": {}})["columns"][col] = {
                "type": _normalize(row.get("COLUMN_TYPE")),
                "nullable": _normalize(row.get("IS_NULLABLE")) or "unknown",
                "key": "PRI" if _normalize(row.get("COLUMN_KEY")) == "PRI" else "",
                "comment": _normalize(row.get("COLUMN_COMMENT")),
            }
        return tables

    raise ValueError(f"merge refresh does not support db_type={db_type}")


async def _existing_graph_state(graph) -> dict:
    result = await graph.query(
        """
        MATCH (c:Column)-[:BELONGS_TO]->(t:Table)
        RETURN t.name, c.name, c.type, c.nullable, c.key_type,
               c.description, c.sample_values
        """
    )
    state: dict[str, dict] = {}
    for row in result.result_set or []:
        table, col = _normalize(row[0]), _normalize(row[1])
        if not table or not col:
            continue
        state.setdefault(table, {})[col] = {
            "type": _normalize(row[2]),
            "nullable": _normalize(row[3]),
            "key": _normalize(row[4]),
            "description": _normalize(row[5]),
            "samples": _normalize(row[6]),
        }
    return state


def _generate_missing_descriptions(
    table_name: str,
    missing: list[str],
    db_columns: dict[str, dict],
    existing_columns: dict[str, dict],
    user_rules: str,
) -> dict[str, str]:
    """One LLM call per table: describe columns that have no description.

    Context: the table name, its other columns with their known descriptions,
    and the user's business rules — so generated wording matches the domain
    conventions already in play.
    """
    from api.agents.utils import run_completion  # pylint: disable=import-outside-toplevel

    sibling_lines = []
    for col, info in sorted(existing_columns.items()):
        if info.get("description"):
            sibling_lines.append(f"- {col} ({info.get('type')}): {info['description'][:160]}")
    target_lines = [
        f"- {col} ({db_columns[col].get('type')})" for col in missing
    ]
    prompt = (
        "You document database columns for a text-to-SQL system.\n"
        f"Table: {table_name}\n"
        "Known sibling columns with descriptions:\n"
        + ("\n".join(sibling_lines[:40]) or "(none)") + "\n\n"
        "Business rules context (wording conventions):\n"
        + (user_rules or "")[:2500] + "\n\n"
        "Write a concise business description (one sentence, same language as "
        "the sibling descriptions, default Russian) for EACH of these columns:\n"
        + "\n".join(target_lines)
        + "\n\nReturn ONLY a JSON object {\"column_name\": \"description\"}."
    )
    try:
        response = run_completion(
            [{"role": "user", "content": prompt}],
            temperature=0,
            max_tokens=1500,
        )
        start = response.find("{")
        end = response.rfind("}")
        parsed = json.loads(response[start:end + 1])
        return {
            _normalize(k): _normalize(v)
            for k, v in parsed.items()
            if _normalize(k) in missing and _normalize(v)
        }
    except Exception as exc:  # pylint: disable=broad-exception-caught
        logging.warning(
            "LLM description generation failed for %s: %s",
            table_name, str(exc)[:200],
        )
        return {}


def _generate_table_description(
    table_name: str, columns_with_desc: list, pk_cols: list, fk_targets: list,
    user_rules: str = "",
) -> str:
    """One LLM call → a concise sentence: WHAT the table represents + its ROW
    GRAIN, from its own columns + PK + FK targets. Replaces the placeholder
    'Table: <name>' so the finder/reranker can pick the right SOURCE table by
    meaning (the owner's "needed tables must be selected by descriptions").
    General — derived from the table's own real metadata, no DB literals."""
    from api.agents.utils import run_completion  # pylint: disable=import-outside-toplevel
    import re as _re  # pylint: disable=import-outside-toplevel
    collines = []
    for nm, ty, d in columns_with_desc[:30]:
        first = (str(d or "").split(". ")[0])[:80]
        collines.append(f"- {nm} ({ty}): {first}")
    prompt = (
        "Document a database TABLE for text-to-SQL. In ONE concise sentence "
        "(<=30 words, same language as the column meanings, default English) say "
        "WHAT this table represents and its ROW GRAIN (one row per ...). "
        "No preamble — only the sentence.\n"
        f"Table: {table_name}\nPrimary key: {', '.join(pk_cols) or '(unknown)'}\n"
        f"References tables: {', '.join(fk_targets) or '(none)'}\n"
        "Columns:\n" + ("\n".join(collines) or "(none)")
    )
    try:
        resp = run_completion([{"role": "user", "content": prompt}],
                              temperature=0, max_tokens=90)
        out = _re.sub(r"<[^>]{0,24}\|?>", "", _normalize(resp))
        out = _re.sub(r"\s+", " ", out).strip().strip('"')
        return out.split("\n")[0][:300]
    except Exception as exc:  # pylint: disable=broad-exception-caught
        logging.warning("table-description LLM failed for %s: %s", table_name, str(exc)[:160])
        return ""


async def backfill_table_descriptions(
    graph, embedding_model, user_rules: str = "", only_placeholders: bool = True,
) -> int:
    """Replace placeholder table descriptions ('Table: X') with real ones derived
    from each table's own columns + PK + FK, IN PLACE (description + embedding;
    columns untouched). Idempotent: a table that already has a real description
    is skipped. Index-time; general (no DB/domain literals)."""
    try:
        trows = await graph.query("MATCH (t:Table) RETURN t.name, t.description")
        tables = [(r[0], r[1]) for r in (trows.result_set or []) if r and r[0]]
    except Exception as exc:  # pylint: disable=broad-exception-caught
        logging.warning("backfill list failed: %s", str(exc)[:160])
        return 0
    done = 0
    for tname, tdesc in tables:
        cur = _normalize(tdesc)
        if only_placeholders and cur and cur.lower() not in (
            f"table {tname}.".lower(), f"table: {tname}".lower(), f"table {tname}".lower(),
        ):
            continue
        try:
            crows = (await graph.query(
                "MATCH (c:Column)-[:BELONGS_TO]->(:Table {name: $t}) "
                "RETURN c.name, c.type, c.key_type, c.description", {"t": tname})).result_set
        except Exception:  # pylint: disable=broad-exception-caught
            continue
        cols, pk = [], []
        for cr in (crows or []):
            cn = cr[0] if len(cr) > 0 else None
            if not cn:
                continue
            cols.append((cn, (cr[1] if len(cr) > 1 else "") or "",
                         _normalize(cr[3] if len(cr) > 3 else "")))
            if (((cr[2] if len(cr) > 2 else "") or "").upper()) in ("PRI", "PK", "PRIMARY KEY"):
                pk.append(cn)
        if not cols:
            continue
        try:
            fkrows = (await graph.query(
                "MATCH (c:Column)-[:BELONGS_TO]->(:Table {name: $t}) "
                "MATCH (c)-[:REFERENCES]->(:Column)-[:BELONGS_TO]->(tgt:Table) "
                "RETURN DISTINCT tgt.name", {"t": tname})).result_set
            fk = [r[0] for r in (fkrows or []) if r and r[0]]
        except Exception:  # pylint: disable=broad-exception-caught
            fk = []
        nd = _generate_table_description(tname, cols, pk, fk, user_rules)
        if not nd:
            continue
        try:
            await graph.query(
                "MATCH (t:Table {name: $t}) SET t.description=$d, t.embedding=vecf32($e)",
                {"t": tname, "d": nd, "e": embedding_model.embed(nd)[0]})
            done += 1
        except Exception as exc:  # pylint: disable=broad-exception-caught
            logging.warning("backfill set failed for %s: %s", tname, str(exc)[:160])
    return done


def _collect_value_preview(
    loader_class,
    db_url: str,
    db_type: str,
    table_name: str,
    column_name: str,
    limit: int = 6,
) -> list[str]:
    quote = "`" if db_type == "impala" or db_type == "mysql" else '"'
    try:
        table_ref = ".".join(
            _quote_sql_identifier(part, quote) for part in table_name.split(".")
        )
        column_ref = _quote_sql_identifier(column_name, quote)
    except Exception:  # pylint: disable=broad-exception-caught
        return []
    # Most-frequent values first — see yaml_loader sampler note.
    sql = (
        f"SELECT {column_ref} AS v, COUNT(*) AS cnt FROM {table_ref} "
        f"WHERE {column_ref} IS NOT NULL "
        f"GROUP BY {column_ref} ORDER BY cnt DESC LIMIT {limit}"
    )
    try:
        rows = loader_class.execute_sql_query(sql, db_url)
    except Exception:  # pylint: disable=broad-exception-caught
        return []
    values = []
    for row in rows or []:
        value = _normalize(list(row.values())[0] if row else "")
        if value:
            values.append(value[:120])
    return values


async def merge_refresh_graph_schema(  # pylint: disable=too-many-locals,too-many-branches,too-many-statements
    loader_class,
    graph_id: str,
    db_url: str,
    db_type: str,
    db=None,
) -> tuple[bool, str]:
    """Refresh a db-backed graph in place. Returns (success, message)."""
    from api.config import Config  # pylint: disable=import-outside-toplevel
    from api.core.db_resolver import resolve_db  # pylint: disable=import-outside-toplevel

    graph = resolve_db(db).select_graph(graph_id)

    db_name = (db_url.rsplit("/", 1)[-1].split("?")[0]) or graph_id.split("_")[-1]
    try:
        fresh = _introspect_database(loader_class, db_url, db_type, db_name)
    except Exception as exc:  # pylint: disable=broad-exception-caught
        logging.error("Refresh introspection failed: %s", str(exc)[:300])
        return False, f"Could not introspect database: {str(exc)[:200]}"
    if not fresh:
        return False, "Database introspection returned no tables; refresh aborted."

    existing = await _existing_graph_state(graph)

    try:
        from api.graph import get_user_rules  # pylint: disable=import-outside-toplevel
        user_rules = await get_user_rules(graph_id, db=db)
    except Exception:  # pylint: disable=broad-exception-caught
        user_rules = ""

    embedding_model = Config.EMBEDDING_MODEL

    added_tables = added_columns = updated_types = removed_tables = removed_columns = 0
    described_by_llm = 0
    previews_added = 0

    # --- removals: objects gone from the database (the DB is the fact) ----
    for table_name in list(existing.keys()):
        if table_name not in fresh:
            await graph.query(
                "MATCH (c:Column)-[:BELONGS_TO]->(t:Table {name: $t}) "
                "DETACH DELETE c, t",
                {"t": table_name},
            )
            removed_tables += 1
    for table_name, db_columns in fresh.items():
        graph_columns = existing.get(table_name, {})
        for col in list(graph_columns.keys()):
            if col not in db_columns["columns"]:
                await graph.query(
                    "MATCH (c:Column {name: $c})-[:BELONGS_TO]->"
                    "(:Table {name: $t}) DETACH DELETE c",
                    {"c": col, "t": table_name},
                )
                removed_columns += 1

    # --- adds / updates -----------------------------------------------------
    for table_name, info in fresh.items():
        db_columns = info["columns"]
        graph_columns = existing.get(table_name, {})
        is_new_table = table_name not in existing

        if is_new_table:
            description = f"Table {table_name}."
            embedding = embedding_model.embed(description)[0]
            await graph.query(
                """
                MERGE (t:Table {name: $t})
                SET t.description = coalesce(t.description, $d),
                    t.embedding = vecf32($e)
                """,
                {"t": table_name, "d": description, "e": embedding},
            )
            added_tables += 1

        # LLM descriptions for columns with no description anywhere
        missing_desc = [
            col for col, meta in db_columns.items()
            if not _normalize(meta.get("comment"))
            and not _normalize((graph_columns.get(col) or {}).get("description"))
        ]
        generated: dict[str, str] = {}
        if missing_desc:
            generated = _generate_missing_descriptions(
                table_name, missing_desc, db_columns, graph_columns, user_rules,
            )
            described_by_llm += len(generated)

        for col, meta in db_columns.items():
            current = graph_columns.get(col)
            db_type_str = meta.get("type") or "unknown"
            if current is None:
                description = (
                    _normalize(meta.get("comment"))
                    or generated.get(col)
                    or f"Column {col} of {table_name}"
                )
                embedding = embedding_model.embed(description)[0]
                samples: list[str] = []
                if _is_sample_candidate(col, {"type": db_type_str, "key": meta.get("key")}):
                    samples = _collect_value_preview(
                        loader_class, db_url, db_type, table_name, col,
                    )
                    if samples:
                        previews_added += 1
                await graph.query(
                    """
                    MATCH (t:Table {name: $t})
                    CREATE (c:Column {name: $c, type: $type, nullable: $n,
                        key_type: $k, description: $d,
                        sample_values: $s, embedding: vecf32($e)})
                    -[:BELONGS_TO]->(t)
                    """,
                    {
                        "t": table_name, "c": col, "type": db_type_str,
                        "n": meta.get("nullable") or "unknown",
                        "k": meta.get("key") or "",
                        "d": description,
                        "s": json.dumps(samples, ensure_ascii=False),
                        "e": embedding,
                    },
                )
                added_columns += 1
                continue

            # existing column: DB wins on structure, enrichment survives
            sets = []
            params: dict[str, Any] = {"t": table_name, "c": col}
            if db_type_str and db_type_str != current.get("type"):
                sets.append("c.type = $type")
                params["type"] = db_type_str
                updated_types += 1
            if not current.get("description"):
                new_desc = _normalize(meta.get("comment")) or generated.get(col)
                if new_desc:
                    sets.append("c.description = $d")
                    sets.append("c.embedding = vecf32($e)")
                    params["d"] = new_desc
                    params["e"] = embedding_model.embed(new_desc)[0]
            empty_samples = current.get("samples") in ("", "[]", "null")
            if empty_samples and _is_sample_candidate(
                col, {"type": db_type_str, "key": current.get("key")},
            ):
                samples = _collect_value_preview(
                    loader_class, db_url, db_type, table_name, col,
                )
                if samples:
                    sets.append("c.sample_values = $s")
                    params["s"] = json.dumps(samples, ensure_ascii=False)
                    previews_added += 1
            if sets:
                await graph.query(
                    "MATCH (c:Column {name: $c})-[:BELONGS_TO]->"
                    "(:Table {name: $t}) SET " + ", ".join(sets),
                    params,
                )

    message = (
        f"Schema refreshed in place: +{added_tables} tables, "
        f"+{added_columns} columns, {updated_types} type updates, "
        f"-{removed_tables} tables, -{removed_columns} columns removed, "
        f"{described_by_llm} descriptions generated by LLM, "
        f"{previews_added} value previews collected. Existing descriptions "
        f"and declared relationships preserved."
    )
    logging.info("Merge refresh %s: %s", graph_id, message)
    return True, message
